### ISSUE TITLE
error: Segmentation fault: 11

### ISSUE THREAD

**Issue by brcbydr** [Rahul-Mayani/RRSocialLogin#1]
Hi,
I need help about "error: Segmentation fault: 11" compiler issue.
When I add below code to my viewController, getting that error:

```
googleButton.rx.tap.bind{ [weak self] _ in
    guard let strongSelf = self else {return}
    RRGoogleLogin.shared.googleSignIn(viewController: strongSelf)
}.disposed(by: rxbag)
```

I have checked the error and it is known XCode bug but couldn't find the solution. 
Please let me know if you have any idea.

Thanks!

**Comment by Rahul-Mayani** [comment]
I have checked sample code and its working perfectly. Not found any compiler error. Please refer the sample code...

**Comment by brcbydr** [comment]
So sorry @Rahul-Mayani, I found the reason. My googlebutton was not UIButton, it's type was GoogleSignInButton. Closing the bug, thanks.
